const carparkTypes = {
	BASEMENT: "BASEMENT CAR PARK",
	MULTISTOREY: "MULTI-STOREY CAR PARK",
	SURFACE: "SURFACE CAR PARK",
	MECHANISM: "MECHANISED CAR PARK",
	COVERED: "COVERED CAR PARK",
	MECHANISED_AND_SURFACE: "MECHANISED AND SURFACE CAR PARK",
	SURFACE_AND_MULTISTOREY: "SURFACE/MULTI-STOREY CAR PARK"
};

const systemTypes = {
    ELECTRONIC: "ELECTRONIC PARKING",
    COUPON: "COUPON PARKING"
}

module.exports = {
    carparkTypes,
    systemTypes
}